name: gcp-auth-and-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write    # required for OIDC → WIF

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/831590811935/locations/global/workloadIdentityPools/gh-pl-customer-pool/providers/gh-oidc
          service_account: tredence-gap-tf-sa@gap-poc-project-1.iam.gserviceaccount.com
          project_id: gap-poc-project-1

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v3

      # Sanity checks (replace with your real steps)
      - name: Who am I?
        run: gcloud auth list && gcloud config list

      - name: List buckets (optional)
        run: gcloud storage buckets list --project gap-poc-project-1 || true
